apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jw8sm9q4x-nodejs 
  janus-idp.io/tekton: jw8sm9q4x-nodejs
  backstage.io/kubernetes-id: jw8sm9q4x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jw8sm9q4x-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml