apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jw8sm9q4x-nodejs
  janus-idp.io/tekton: jw8sm9q4x-nodejs
  backstage.io/kubernetes-id: jw8sm9q4x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jw8sm9q4x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
