apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jw8sm9q4x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jw8sm9q4x-nodejs 
  name: jw8sm9q4x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jw8sm9q4x-nodejs 
