apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jw8sm9q4x-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:317233a4c81efeea9310e7aa81453a7b35365d5c@sha256:811fbde78d51b06454f0e687e9b7d4fb4ddf6b55cb828c59fb6756126276d8f5
          name: container-image
